# Generated by Django 3.0.4 on 2020-03-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='user_id',
            new_name='requester',
        ),
    ]
