# Generated by Django 3.0.4 on 2020-03-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200319_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
